DROP TABLE IF EXISTS 2024_albums;
CREATE TABLE 2024_albums (
  id         INT AUTO_INCREMENT NOT NULL,
  album      VARCHAR(255) NOT NULL,
  artist     VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO 2024_albums
  (album, artist)
VALUES
  ( "Marvin Gaye", "What's Going On" ),
  ( "The Beach Boys", "Pet Sounds" ),
  ( "Joni Mitchell", "Blue" ),
  ( "Stevie Wonder", "Songs In The Key Of Life" ),
  ( "The Beatles", "Abbey Road" ),
  ( "Nirvana", "Nevermind" ),
  ( "Fleetwood Mac", "Rumours" ),
  ( "Prince And The Revolution", "Purple Rain" ),
  ( "Bob Dylan", "Blood On The Tracks" ),
  ( "Lauryn Hill", "The Miseducation Of Lauryn Hill" ),
  ( "The Beatles", "Revolver" ),
  ( "Michael Jackson", "Thriller" ),
  ( "Aretha Franklin", "I Never Loved A Man The Way I Love You" ),
  ( "Rolling Stones*", "Exile On Main St" ),
  ( "Public Enemy", "It Takes A Nation Of Millions To Hold Us Back" ),
  ( "The Clash", "London Calling" ),
  ( "Kanye West", "My Beautiful Dark Twisted Fantasy" ),
  ( "Bob Dylan", "Highway 61 Revisited" ),
  ( "Kendrick Lamar", "To Pimp A Butterfly" ),
  ( "Radiohead", "Kid A" ),
  ( "Bruce Springsteen", "Born To Run" ),
  ( "The Notorious B.I.G.*", "Ready To Die" ),
  ( "The Velvet Underground &amp; Nico (3)", "The Velvet Underground &amp; Nico" ),
  ( "The Beatles", "Sgt. Pepper's Lonely Hearts Club Band" ),
  ( "Carole King", "Tapestry" ),
  ( "Patti Smith", "Horses" ),
  ( "Wu-Tang Clan", "Enter The Wu-Tang (36 Chambers)" ),
  ( "D'Angelo", "Voodoo" ),
  ( "The Beatles", "The Beatles" ),
  ( "The Jimi Hendrix Experience", "Are You Experienced" ),
  ( "Miles Davis", "Kind Of Blue" ),
  ( "Beyoncé", "Lemonade" ),
  ( "Amy Winehouse", "Back To Black" ),
  ( "Stevie Wonder", "Innervisions" ),
  ( "The Beatles", "Rubber Soul" ),
  ( "Michael Jackson", "Off The Wall" ),
  ( "Dr. Dre", "The Chronic" ),
  ( "Bob Dylan", "Blonde On Blonde" ),
  ( "Talking Heads", "Remain In Light" ),
  ( "David Bowie", "The Rise And Fall Of Ziggy Stardust And The Spiders From Mars" ),
  ( "Rolling Stones*", "Let It Bleed" ),
  ( "Radiohead", "OK Computer" ),
  ( "A Tribe Called Quest", "The Low End Theory" ),
  ( "Nas", "Illmatic" ),
  ( "Prince", "Sign \"O\" The Times" ),
  ( "Paul Simon", "Graceland" ),
  ( "Ramones", "Ramones" ),
  ( "Bob Marley &amp; The Wailers", "Legend (The Best Of Bob Marley And The Wailers)" ),
  ( "OutKast", "Aquemini" ),
  ( "Jay-Z", "The Blueprint" ),
  ( "Chuck Berry", "The Great Twenty-Eight" ),
  ( "David Bowie", "Station To Station" ),
  ( "The Jimi Hendrix Experience", "Electric Ladyland" ),
  ( "James Brown", "Star Time" ),
  ( "Pink Floyd", "The Dark Side Of The Moon" ),
  ( "Liz Phair", "Exile In Guyville" ),
  ( "The Band", "The Band" ),
  ( "Led Zeppelin", "Untitled" ),
  ( "Stevie Wonder", "Talking Book" ),
  ( "Van Morrison", "Astral Weeks" ),
  ( "Eric B. &amp; Rakim", "Paid In Full" ),
  ( "Guns N' Roses", "Appetite For Destruction" ),
  ( "Steely Dan", "Aja" ),
  ( "OutKast", "Stankonia" ),
  ( "James Brown", "The James Brown Show (Live At The Apollo)" ),
  ( "John Coltrane", "A Love Supreme" ),
  ( "Jaÿ-Z*", "Reasonable Doubt" ),
  ( "Kate Bush", "Hounds Of Love" ),
  ( "Alanis Morissette", "Jagged Little Pill" ),
  ( "N.W.A*", "Straight Outta Compton" ),
  ( "Bob Marley &amp; The Wailers", "Exodus" ),
  ( "Neil Young", "Harvest" ),
  ( "My Bloody Valentine", "Loveless" ),
  ( "Kanye West", "The College Dropout" ),
  ( "Aretha Franklin", "Lady Soul" ),
  ( "Curtis Mayfield", "Superfly" ),
  ( "The Who", "Who's Next" ),
  ( "Elvis Presley", "The Elvis Presley Sun Collection" ),
  ( "Frank Ocean", "Blond" ),
  ( "Sex Pistols", "Never Mind The Bollocks Here's The Sex Pistols" ),
  ( "Beyoncé", "Beyoncé" ),
  ( "Sly &amp; The Family Stone", "There's A Riot Goin' On" ),
  ( "Dusty Springfield", "Dusty In Memphis" ),
  ( "AC/DC", "Back In Black" ),
  ( "John Lennon / Plastic Ono Band*", "John Lennon / Plastic Ono Band" ),
  ( "The Doors", "The Doors" ),
  ( "Miles Davis", "Bitches Brew" ),
  ( "David Bowie", "Hunky Dory" ),
  ( "Erykah Badu", "Baduizm" ),
  ( "Neil Young", "After The Gold Rush" ),
  ( "Bruce Springsteen", "Darkness On The Edge Of Town" ),
  ( "The Jimi Hendrix Experience", "Axis: Bold As Love" ),
  ( "Missy \"Misdemeanor\" Elliott*", "Supa Dupa Fly" ),
  ( "The Stooges", "Fun House" ),
  ( "Drake", "Take Care" ),
  ( "R.E.M.", "Automatic For The People" ),
  ( "Metallica", "Master Of Puppets" ),
  ( "Lucinda Williams", "Car Wheels On A Gravel Road" ),
  ( "Taylor Swift", "Red" ),
  ( "The Band", "Music From Big Pink" ),
  ( "Led Zeppelin", "Led Zeppelin" ),
  ( "The Clash", "The Clash" ),
  ( "De La Soul", "3 Feet High And Rising" ),
  ( "The Rolling Stones", "Sticky Fingers" ),
  ( "The Allman Brothers Band", "The Allman Brothers Band At Fillmore East" ),
  ( "Hole (2)", "Live Through This" ),
  ( "Television", "Marquee Moon" ),
  ( "Fiona Apple", "When The Pawn Hits The Conflicts He Thinks Like A King What He Knows Throws The Blows When He Goes To The Fight And He'll Win The Whole Thing 'Fore He Enters The Ring There's No Body To Batter When Your Mind Is Your Might So When You Go Solo, You Hold You" ),
  ( "Lou Reed", "Transformer" ),
  ( "Joni Mitchell", "Court And Spark" ),
  ( "Janet Jackson", "Control" ),
  ( "Elton John", "Goodbye Yellow Brick Road" ),
  ( "The Smiths", "The Queen Is Dead" ),
  ( "The Strokes", "Is This It" ),
  ( "Kendrick Lamar", "Good Kid, M.A.A.d City" ),
  ( "The Cure", "Disintegration" ),
  ( "Kanye West", "Late Registration" ),
  ( "Eagles", "Hotel California" ),
  ( "Sly And The Family Stone*", "Stand!" ),
  ( "Van Morrison", "Moondance" ),
  ( "Elvis Costello &amp; The Attractions", "This Year's Model" ),
  ( "Nine Inch Nails", "The Downward Spiral" ),
  ( "Led Zeppelin", "Led Zeppelin II" ),
  ( "U2", "Achtung Baby" ),
  ( "Beastie Boys", "Paul's Boutique" ),
  ( "Mary J. Blige", "My Life" ),
  ( "Ray Charles", "Modern Sounds In Country And Western Music" ),
  ( "Queen", "A Night At The Opera" ),
  ( "Pink Floyd", "The Wall" ),
  ( "Prince", "1999" ),
  ( "Portishead", "Dummy" ),
  ( "Hank Williams", "40 Greatest Hits" ),
  ( "Joni Mitchell", "Hejira" ),
  ( "Fugees", "The Score" ),
  ( "U2", "The Joshua Tree" ),
  ( "Funkadelic", "Maggot Brain" ),
  ( "Adele (3)", "21" ),
  ( "Madonna", "The Immaculate Collection" ),
  ( "Black Sabbath", "Paranoid" ),
  ( "The Wailers", "Catch A Fire" ),
  ( "Pixies", "Doolittle" ),
  ( "Bruce Springsteen", "Born In The U.S.A." ),
  ( "The Velvet Underground", "The Velvet Underground" ),
  ( "Led Zeppelin", "Physical Graffiti" ),
  ( "Eminem", "The Marshall Mathers LP" ),
  ( "Blondie", "Parallel Lines" ),
  ( "Jeff Buckley", "Grace" ),
  ( "Frank Ocean", "Channel Orange" ),
  ( "John Prine", "John Prine" ),
  ( "Bruce Springsteen", "Nebraska" ),
  ( "George Michael", "Faith" ),
  ( "Pretenders*", "Pretenders" ),
  ( "Aretha Franklin With James Cleveland* &amp; The Southern California Community Choir", "Amazing Grace" ),
  ( "P J Harvey*", "Rid Of Me" ),
  ( "Jay-Z", "The Black \"album\"" ),
  ( "The Replacements", "Let It Be" ),
  ( "Oasis (2)", "(What's The Story) Morning Glory?" ),
  ( "eryKahBadu*", "Mama's Gun" ),
  ( "The Police", "Synchronicity" ),
  ( "Pearl Jam", "Ten" ),
  ( "Crosby, Stills &amp; Nash", "Crosby, Stills &amp; Nash" ),
  ( "Pulp", "Different Class" ),
  ( "Various", "Saturday Night Fever (The Original Movie Sound Track)" ),
  ( "Johnny Cash", "At Folsom Prison" ),
  ( "R.E.M.", "Murmur" ),
  ( "Buddy Holly &amp; The Crickets (2)", "20 Golden Greats" ),
  ( "Depeche Mode", "Violator" ),
  ( "Steely Dan", "Can't Buy A Thrill" ),
  ( "Billy Joel", "The Stranger" ),
  ( "Cream (2)", "Disraeli Gears" ),
  ( "Sonic Youth", "Daydream Nation" ),
  ( "Simon And Garfunkel*", "Bridge Over Troubled Water" ),
  ( "Nirvana", "In Utero" ),
  ( "Various", "The Harder They Come (Original Soundtrack Recording)" ),
  ( "Kendrick Lamar", "Damn" ),
  ( "Public Enemy", "Fear Of A Black Planet" ),
  ( "Rod Stewart", "Every Picture Tells A Story" ),
  ( "Otis Redding", "Otis Blue / Otis Redding Sings Soul" ),
  ( "The Notorious B.I.G.*", "Life After Death" ),
  ( "Love", "Forever Changes" ),
  ( "Bob Dylan", "Bringing It All Back Home" ),
  ( "James Taylor (2)", "Sweet Baby James" ),
  ( "D'Angelo", "Brown Sugar" ),
  ( "Cyndi Lauper", "She's So Unusual" ),
  ( "Rolling Stones*", "Beggars Banquet" ),
  ( "Red Hot Chili Peppers", "Blood Sugar Sex Magik" ),
  ( "Ice Cube", "AmeriKKKa's Most Wanted" ),
  ( "T. Rex", "Electric Warrior" ),
  ( "Sleater-Kinney", "Dig Me Out" ),
  ( "The Who", "Tommy" ),
  ( "Etta James", "At Last!" ),
  ( "Beastie Boys", "Licensed To Ill" ),
  ( "Creedence Clearwater Revival", "Willy And The Poor Boys" ),
  ( "Michael Jackson", "Bad" ),
  ( "Leonard Cohen", "Songs Of Leonard Cohen" ),
  ( "Robyn", "Body Talk" ),
  ( "The Beatles", "Meet The Beatles!" ),
  ( "The B-52's", "The B-52's" ),
  ( "Pavement", "Slanted And Enchanted" ),
  ( "Sade", "Diamond Life" ),
  ( "A Tribe Called Quest", "Midnight Marauders" ),
  ( "Björk", "Homogenic" ),
  ( "Nick Drake", "Pink Moon" ),
  ( "kanYeWest*", "Graduation" ),
  ( "Cat Stevens", "Tea For The Tillerman" ),
  ( "David Bowie", "Low" ),
  ( "Eagles", "Eagles" ),
  ( "Lil Wayne", "Tha Carter III" ),
  ( "Run DMC*", "Raising Hell" ),
  ( "Ray Charles", "The Complete Atlantic Rhythm &amp; Blues Recordings 1952-1959" ),
  ( "Joy Division", "Unknown Pleasures" ),
  ( "Nina Simone", "Wild Is The Wind" ),
  ( "Fiona Apple", "The Idler Wheel Is Wiser Than The Driver Of The Screw And Whipping Cords Will Serve You More Than Ropes Will Ever Do" ),
  ( "Tom Petty", "Wildflowers" ),
  ( "Grateful Dead*", "American Beauty" ),
  ( "Elliott Smith", "Either / Or" ),
  ( "Oasis (2)", "Definitely Maybe" ),
  ( "TLC", "CrazySexyCool" ),
  ( "Chef Raekwon* Guest Starring: Ghost Face Killer* A/K/A Tony Starks", "Only Built 4 Cuban Linx..." ),
  ( "Crosby, Stills, Nash &amp; Young", "Déjà Vu" ),
  ( "Rage Against The Machine", "Rage Against The Machine" ),
  ( "Madonna", "Ray Of Light" ),
  ( "John Lennon", "Imagine" ),
  ( "Dixie Chicks", "Fly" ),
  ( "Wilco", "Yankee Hotel Foxtrot" ),
  ( "Derek And The Dominos*", "Layla And Other Assorted Love Songs" ),
  ( "Little Richard", "Here's Little Richard" ),
  ( "De La Soul", "De La Soul Is Dead" ),
  ( "Patsy Cline", "The Ultimate Collection" ),
  ( "Rihanna", "Anti" ),
  ( "Tom Petty And The Heartbreakers", "Damn The Torpedoes" ),
  ( "John Coltrane", "Giant Steps" ),
  ( "Tori Amos", "Little Earthquakes" ),
  ( "Black Sabbath", "Master Of Reality" ),
  ( "Metallica", "Metallica" ),
  ( "Daft Punk", "Discovery" ),
  ( "Willie Nelson", "Red Headed Stranger" ),
  ( "Kraftwerk", "Trans Europa Express" ),
  ( "Boogie Down Productions", "Criminal Minded" ),
  ( "Sam Cooke", "Live At The Harlem Square Club, 1963" ),
  ( "Massive*", "Blue Lines" ),
  ( "The Velvet Underground", "Loaded" ),
  ( "The Zombies", "Odessey And Oracle" ),
  ( "Kanye West", "808s &amp; Heartbreak" ),
  ( "Cocteau Twins", "Heaven Or Las Vegas" ),
  ( "L.L. Cool J*", "Mama Said Knock You Out" ),
  ( "Sade", "Love Deluxe" ),
  ( "Green Day", "American Idiot" ),
  ( "Whitney Houston", "Whitney Houston" ),
  ( "Buzzcocks", "Singles Going Steady" ),
  ( "Elton John", "Honky Château" ),
  ( "Devo", "Q: Are We Not Men? A: We Are Devo!" ),
  ( "Pink Floyd", "The Piper At The Gates Of Dawn" ),
  ( "Herbie Hancock", "Head Hunters" ),
  ( "Bob Dylan", "The Freewheelin' Bob Dylan" ),
  ( "Tracy Chapman", "Tracy Chapman" ),
  ( "Dolly Parton", "Coat Of Many Colors" ),
  ( "Joni Mitchell", "The Hissing Of Summer Lawns" ),
  ( "Janis Joplin", "Pearl" ),
  ( "The Slits", "Cut" ),
  ( "Beastie Boys", "Check Your Head" ),
  ( "New Order", "Power, Corruption &amp; Lies" ),
  ( "The Beatles", "A Hard Day's Night" ),
  ( "Pink Floyd", "Wish You Were Here" ),
  ( "Pavement", "Wowee Zowee" ),
  ( "The Beatles", "Help!" ),
  ( "Minutemen", "Double Nickels On The Dime" ),
  ( "Randy Newman", "Sail Away" ),
  ( "Kanye West", "Yeezus" ),
  ( "Kacey Musgraves", "Golden Hour" ),
  ( "Mary J. Blige", "What's The 411?" ),
  ( "The Velvet Underground", "White Light/White Heat" ),
  ( "Gang Of Four", "Entertainment!" ),
  ( "The Byrds", "Sweetheart Of The Rodeo" ),
  ( "Curtis Mayfield", "Curtis" ),
  ( "Radiohead", "The Bends" ),
  ( "Alicia Keys", "The Diary Of Alicia Keys" ),
  ( "Led Zeppelin", "Houses Of The Holy" ),
  ( "Nirvana", "MTV Unplugged In New York" ),
  ( "50 Cent", "Get Rich Or Die Tryin'" ),
  ( "Nilsson*", "Nilsson Schmilsson" ),
  ( "Frank Sinatra", "In The Wee Small Hours" ),
  ( "Donna Summer", "Bad Girls" ),
  ( "Merle Haggard", "Down Every Road (1962-1994)" ),
  ( "Big Star", "3rd" ),
  ( "Red Hot Chili Peppers", "Californication" ),
  ( "The Byrds", "Mr. Tambourine Man" ),
  ( "The Modern Lovers", "The Modern Lovers" ),
  ( "Björk", "Post" ),
  ( "OutKast", "Speakerboxxx / The Love Below" ),
  ( "Destiny's Child", "The Writing's On The Wall" ),
  ( "Van Halen", "Van Halen" ),
  ( "The Breeders", "Last Splash" ),
  ( "Weezer", "Weezer" ),
  ( "Daft Punk", "Random Access Memories" ),
  ( "Neil Young &amp; Crazy Horse", "Rust Never Sleeps" ),
  ( "Peter Gabriel", "So" ),
  ( "Tom Petty", "Full Moon Fever" ),
  ( "B.B. King", "Live At The Regal" ),
  ( "Shania Twain", "Come On Over" ),
  ( "New York Dolls", "New York Dolls" ),
  ( "Neil Young", "Tonight's The Night" ),
  ( "ABBA", "The Definitive Collection" ),
  ( "Bill Withers", "Just As I Am" ),
  ( "Kiss", "Alive!" ),
  ( "Al Green", "I'm Still In Love With You" ),
  ( "Sam Cooke", "Portrait Of A Legend 1951-1964" ),
  ( "Eno*", "Here Come The Warm Jets" ),
  ( "Joy Division", "Closer" ),
  ( "Wire", "Pink Flag" ),
  ( "Neil Young", "On The Beach" ),
  ( "Solange (2)", "A Seat At The Table" ),
  ( "P J Harvey*", "Stories From The City, Stories From The Sea" ),
  ( "Aaliyah", "One In A Million" ),
  ( "Rosalía (3)", "El Mal Querer" ),
  ( "The Who", "The Who Sell Out" ),
  ( "Billie Holiday With Ray Ellis And His Orchestra", "Lady In Satin" ),
  ( "Janet*", "The Velvet Rope" ),
  ( "The Stone Roses", "The Stone Roses" ),
  ( "X (5)", "Los Angeles" ),
  ( "Lana Del Rey", "Norman Fucking Rockwell!" ),
  ( "Elvis Presley", "From Elvis In Memphis" ),
  ( "The Clash", "Sandinista!" ),
  ( "Coldplay", "A Rush Of Blood To The Head" ),
  ( "Jerry Lee Lewis", "All Killer No Filler!" ),
  ( "Prince", "Dirty Mind" ),
  ( "The Who", "Live At Leeds" ),
  ( "Vampire Weekend", "Modern Vampires Of The City" ),
  ( "DJ Shadow", "Endtroducing....." ),
  ( "The Rolling Stones", "Aftermath" ),
  ( "Madonna", "Like A Prayer" ),
  ( "Elvis Presley", "Elvis Presley" ),
  ( "Bill Withers", "Still Bill" ),
  ( "Santana", "Abraxas" ),
  ( "Bob Dylan &amp; The Band", "The Basement Tapes" ),
  ( "Roxy Music", "Avalon" ),
  ( "Bob Dylan", "John Wesley Harding" ),
  ( "Eno*", "Another Green World" ),
  ( "Janet Jackson", "Janet Jackson's Rhythm Nation 1814" ),
  ( "Snoop Doggy Dogg*", "Doggystyle" ),
  ( "Smashing Pumpkins*", "Siamese Dream" ),
  ( "The Beatles", "Let It Be" ),
  ( "Sly &amp; The Family Stone", "Greatest Hits" ),
  ( "Toots &amp; The Maytals", "Funky Kingston" ),
  ( "Bruce Springsteen", "The Wild, The Innocent &amp; The E Street Shuffle" ),
  ( "Arctic Monkeys", "AM" ),
  ( "Genius* / GZA", "Liquid Swords" ),
  ( "Gillian Welch", "Time (The Revelator)" ),
  ( "MC5", "Kick Out The Jams" ),
  ( "Stevie Wonder", "Music Of My Mind" ),
  ( "Roxy Music", "For Your Pleasure" ),
  ( "Eminem", "The Slim Shady LP" ),
  ( "The Cars", "The Cars" ),
  ( "X-Ray Spex", "Germfree Adolescents" ),
  ( "Black Sabbath", "Black Sabbath" ),
  ( "Dr. John, The Night Tripper", "Gris-Gris" ),
  ( "Tom Waits", "Rain Dogs" ),
  ( "Sonic Youth", "Goo" ),
  ( "Big Star", "Radio City" ),
  ( "Funkadelic", "One Nation Under A Groove" ),
  ( "My Chemical Romance", "The Black Parade" ),
  ( "Luther Vandross", "Never Too Much" ),
  ( "Parliament", "Mothership Connection" ),
  ( "Talking Heads", "More Songs About Buildings And Food" ),
  ( "Doom* And Madlib", "Madvillainy" ),
  ( "Aerosmith", "\"Rocks\"" ),
  ( "Drake", "If You're Reading This It's Too Late" ),
  ( "George Harrison", "All Things Must Pass" ),
  ( "Mobb Deep", "The Infamous" ),
  ( "Lil Wayne", "Tha Carter II" ),
  ( "The Temptations", "Anthology" ),
  ( "Big Brother &amp; The Holding Company", "Cheap Thrills" ),
  ( "Isaac Hayes", "Hot Buttered Soul" ),
  ( "Robert Johnson", "King Of The Delta Blues Singers" ),
  ( "Green Day", "Dookie" ),
  ( "Neutral Milk Hotel", "In The Aeroplane Over The Sea" ),
  ( "Yeah Yeah Yeahs", "Fever To Tell" ),
  ( "Run-D.M.C.*", "Run-D.M.C." ),
  ( "Rush", "Moving Pictures" ),
  ( "Charles Mingus", "Mingus Ah Um" ),
  ( "Lynyrd Skynyrd", "(Pronounced 'Lĕh-'nérd 'Skin-'nérd)" ),
  ( "Tame Impala", "Currents" ),
  ( "Massive Attack", "Mezzanine" ),
  ( "The Kinks", "The Kinks Are The Village Green Preservation Society" ),
  ( "Ramones", "Rocket To Russia" ),
  ( "J Dilla", "Donuts" ),
  ( "Radiohead", "In Rainbows" ),
  ( "Aretha Franklin", "Young, Gifted And Black" ),
  ( "Mariah Carey", "The Emancipation Of Mimi" ),
  ( "Pixies", "Surfer Rosa" ),
  ( "Kelis", "Kaleidoscope" ),
  ( "Ike &amp; Tina Turner", "Proud Mary-The Best Of Ike And Tina Turner" ),
  ( "Taylor Swift", "1989" ),
  ( "Diana Ross", "Diana" ),
  ( "D'Angelo And The Vanguard (3)", "Black Messiah" ),
  ( "Todd Rundgren", "Something / Anything?" ),
  ( "Billie Eilish", "When We All Fall Asleep, Where Do We Go?" ),
  ( "The Raincoats", "The Raincoats" ),
  ( "Brian Wilson", "Smile" ),
  ( "Go-Go's", "Beauty And The Beat" ),
  ( "Blondie", "Blondie" ),
  ( "Fela Ransome Kuti* &amp; Africa 70", "Expensive Shit" ),
  ( "Ghostface Killah", "Supreme Clientele" ),
  ( "Anita Baker", "Rapture" ),
  ( "Various", "Nuggets (Original Artyfacts From The First Psychedelic Era 1965-1968)" ),
  ( "The Magnetic Fields", "69 Love Songs" ),
  ( "Neil Young With Crazy Horse", "Everybody Knows This Is Nowhere" ),
  ( "Motörhead", "Ace Of Spades" ),
  ( "The Grateful Dead", "Workingman's Dead" ),
  ( "The Beach Boys", "Wild Honey" ),
  ( "Bob Dylan", "\"Love And Theft\"" ),
  ( "Smokey Robinson And The Miracles*", "Going To A Go-Go" ),
  ( "Creedence Clearwater Revival", "Cosmo's Factory" ),
  ( "Chic", "Risqué" ),
  ( "The Meters", "Look-Ka Py Py" ),
  ( "The Roots", "Things Fall Apart" ),
  ( "Ornette Coleman", "The Shape Of Jazz To Come" ),
  ( "Dire Straits", "Brothers In Arms" ),
  ( "Eric Church", "Chief" ),
  ( "Earth, Wind &amp; Fire", "That's The Way Of The World" ),
  ( "M.I.A. (2)", "Arular" ),
  ( "Marvin Gaye", "Let's Get It On" ),
  ( "Yo La Tengo", "I Can Hear The Heart Beating As One" ),
  ( "Beck!*", "Odelay" ),
  ( "Paul Simon", "Paul Simon" ),
  ( "Lucinda Williams", "Lucinda Williams" ),
  ( "Al Green", "Call Me" ),
  ( "Hüsker Dü", "New Day Rising" ),
  ( "Four Tops", "Four Tops Reach Out" ),
  ( "Elvis Costello", "My Aim Is True" ),
  ( "Los Lobos", "How Will The Wolf Survive?" ),
  ( "Usher", "Confessions" ),
  ( "LCD Soundsystem", "Sound Of Silver" ),
  ( "Pavement", "Crooked Rain, Crooked Rain" ),
  ( "Pet Shop Boys", "Actually" ),
  ( "2Pac", "All Eyez On Me" ),
  ( "Primal Scream", "Screamadelica" ),
  ( "Blur", "Parklife" ),
  ( "James Brown", "Sex Machine" ),
  ( "Loretta Lynn", "Coal Miner's Daughter" ),
  ( "Britney Spears", "Blackout" ),
  ( "The Weeknd", "Beauty Behind The Madness" ),
  ( "David Bowie", "Scary Monsters" ),
  ( "Fiona Apple", "Extraordinary Machine" ),
  ( "Yes", "Close To The Edge" ),
  ( "Alice Coltrane Featuring Pharoah Sanders", "Journey In Satchidananda" ),
  ( "Bad Bunny", "X 100PRE" ),
  ( "Otis Redding", "Complete &amp; Unbelievable" ),
  ( "The White Stripes", "Elephant" ),
  ( "Paul And Linda McCartney*", "Ram" ),
  ( "Roberta Flack", "First Take" ),
  ( "Diana Ross And The Supremes*", "Anthology" ),
  ( "Nine Inch Nails", "Pretty Hate Machine" ),
  ( "Can", "Ege Bamyasi" ),
  ( "Bo Diddley", "Bo Diddley / Go Bo Diddley" ),
  ( "Al Green", "Greatest Hits" ),
  ( "Sinéad O'Connor", "I Do Not Want What I Haven't Got" ),
  ( "Jason Isbell", "Southeastern" ),
  ( "Kid Cudi", "Man On The Moon: The End Of Day" ),
  ( "Lorde", "Melodrama" ),
  ( "Bon Iver", "For Emma, Forever Ago" ),
  ( "The Flying Burrito Bros", "The Gilded Palace Of Sin" ),
  ( "Laura Nyro", "Eli And The Thirteenth Confession" ),
  ( "The Isley Brothers", "3 + 3" ),
  ( "King Sunny Ade", "The Best Of The Classic Years" ),
  ( "The Beach Boys", "The Beach Boys Today!" ),
  ( "Maxwell", "BLACKsummers'night" ),
  ( "The Rolling Stones", "Some Girls" ),
  ( "Manu Chao", "Clandestino" ),
  ( "Juvenile (2)", "400 Degreez" ),
  ( "Jefferson Airplane", "Surrealistic Pillow" ),
  ( "SZA (2)", "Ctrl" ),
  ( "Daddy Yankee", "Barrio Fino" ),
  ( "Big Star", "#1 Record" ),
  ( "Sheryl Crow", "Sheryl Crow" ),
  ( "Sparks", "Kimono My House" ),
  ( "Howlin' Wolf", "Moanin' In The Moonlight" ),
  ( "The Kinks", "Something Else By The Kinks" ),
  ( "Selena", "Amor Prohibido" ),
  ( "Miranda Lambert", "The Weight Of These Wings" ),
  ( "Belle And Sebastian*", "If You're Feeling Sinister" ),
  ( "The Pharcyde", "Bizarre Ride II The Pharcyde" ),
  ( "Muddy Waters", "The Anthology" ),
  ( "Lady Gaga", "Born This Way" ),
  ( "Richard And Linda Thompson*", "I Want To See The Bright Lights Tonight" ),
  ( "John Mayer", "Continuum" ),
  ( "Black Flag", "Damaged" ),
  ( "The Stooges", "The Stooges" ),
  ( "Phil Spector", "Back To Mono (1958-1969)" ),
  ( "Linda Ronstadt", "Heart Like A Wheel" ),
  ( "Harry Styles", "Fine Line" ),
  ( "Bonnie Raitt", "Nick Of Time" ),
  ( "Marvin Gaye", "\"Here, My Dear.\"" ),
  ( "The Ronettes", "...Presenting The Fabulous Ronettes Featuring Veronica" ),
  ( "Boyz II Men", "II" ),
  ( "Shakira", "Dónde Están Los Ladrones?" ),
  ( "Various", "The Indestructible Beat Of Soweto" ),
  ( "Suicide", "Suicide" ),
  ( "Rufus Featuring Chaka Khan*", "Ask Rufus" ),
  ( "Arcade Fire", "Funeral" );
