# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: 'Create env file'
      run: |
        touch .env
        echo URL=localhost >> .env
        echo PORT=8080 >> .env
        echo LOG_TO_FILE=FALSE >> .env
        echo RELEASE_MODE=PROD >> .env
        cat .env

    - name: Test
      run: go test -v ./...
